### ISSUE TITLE
Using a variable for the displayed text

### ISSUE THREAD

**Issue by DuncanAmos** [ridercz/Altairis-ESP8266-FC16#2]
Works great but I need to use a variable for the text to be displayed (it will depend on various parameters and will be a concatenated string).

It won't seem to allow me to do it. As a test, I'm using this within the loop:
  _String countString = String(showCount);
  String outString = ("Pass through loop number " + countString);
  display.setText(outString);_

It throws this error:
_exit status 1
no matching function for call to 'FC16::setText(String&)'_

**Comment by ridercz** [comment]
This should work: `display.setText(outString.c_str());`

**Comment by cmorda** [comment]
That did not work for me. adding this to convert the string to char worked in my case:

  char message[payload.length()];
  payload.toCharArray(message, payload.length());

Maybe this will help someone.
