### ISSUE TITLE
Sending scroll message

### ISSUE THREAD

**Issue by gurues** [ridercz/Altairis-ESP8266-FC16#3]
I'm sending a scrolling message and the first time it works fine but the second time it doesn't scroll the whole message just a few letters. Both times I call update () but the second time it returns true very quickly. It happens to me both with the same message and with a different message. Between both messages I use the clock function to show the time. Is there a special way to use multiple scrolling posts ?. Looking at the documentation I can't find anything. 

Greetings

**Comment by m9aertner** [comment]
Hi. Please post or link to the actual code that does not work for you. I'm sure that it'll be easier for others to understand what the actual problem is. I just tried two of the demos and they worked fine for me.

**Comment by ridercz** [comment]
Versions <1.7.0 do not support displaying clock and scrolling text at the same time. Since version 1.7.0 you can do it (on different displays). See the `TextClock` example on how to do it.
